// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbrgzywltpkuthrxzlgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxicmd6eXdsdHBrdXRocnh6bGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjY3MjksImV4cCI6MjA1OTIwMjcyOX0.LOCsuVKsn5iAT-yaVgeR0YCzIocpkX4QQ9ZHp-Fou4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);